apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-application
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://kubernetes.default.svc
          - cluster: staging
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{cluster}}-redis-app"
    spec:
      project: default
      source:
        repoURL: https://github.com/NinaLee96/argo-cd-test.git
        targetRevision: HEAD
        path: redis-app/{{cluster}}
      destination:
        server: "{{ url }}"
        namespace: redis

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
