apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-deployment
spec:
  selector:
    matchLabels:
      app: cat
  replicas: 2
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
        - name: cat
          image: library/redis:7.0.5
          ports:
            - containerPort: 8080
